name: Create New Issues
on:
  issues:
    types: [labeled]
jobs:
  create-new-issues:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write 
    if: github.event.label.name == 'iOS'
    steps:
    - uses: actions/checkout@v4
    - uses: JasonEtco/create-an-issue@v2.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Issue
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_LABEL: ${{ github.event.label.name }}
      run: 
        echo "$ISSUE_TITLE"
        echo "$ISSUE_LABEL"
