name: Create New Issues
on:
  issues:
    types: [labeled]
jobs:
  create-new-issues:
    if: github.event.label.name == 'iOS'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: JasonEtco/create-an-issue@v2.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Issue
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: echo "$ISSUE_TITLE"
