name: Create New Discussion
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  create-new-discussion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          script: |
            mutation {
            createDiscussion(input: {repositoryId: "MDEwOlJlcG9zaXRvcnkxNTc0OTQ5Mjk=", categoryId: "DIC_kwDOCWMukc4CcNbN", body: "The body", title: "The title"}) {
            discussion {
              id
            }
          }
        }
