name: Create New Discussion
on:
  schedule:
    - cron: '* * * * *'
jobs:
  create-new-discussion:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
    steps:
      - uses: abirismyname/create-discussion@v1.1.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          title: 주간회의 $(date "+%Y/%m/%d")"
          body: |
            주간회의 남겨주세요. 
          repository-id: ${{ secrets.REPO_ID }}
          category-id: ${{ secrets.CAT_ID }}  
      - name: Print discussion url and id
        run: |
          echo discussion-id: ${{steps.create-discussion.outputs.discussion-id}} 
          echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}             
