name: Create New Discussion
on:
  schedule:
    cron: '0 9 * * 5'
jobs:
  create-new-discussion:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussion: write
    steps:
    - name: create new discussion
      id: create-discussion
      uses: abirismyname/create-discussion@v1.1.0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      with:
        title: 주간회의 $(date "+%Y/%m/%d")"
        body: |
          주간회의 남겨주세요. 
        repository-id: ${{ secrets.REPO_ID }}
        category-id: ${{ secrets.CAT_ID }}  
